esphome:
  name: esp32-climate
  friendly_name: ESP32-Climate

esp32:
  board: esp32dev
  framework:
    type: esp-idf


# Configure the inputs
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO15
      mode:
        input: true
        pullup: false
      inverted: true
    name: "Input"
    use_interrupt: True
    filters:
      - delayed_on: 100ms
      - delayed_off: 100ms

# Example configuration entry
sensor:
  - platform: dht
    pin: GPIO19
    model: AM2302
    temperature:
      name: "Living Room Temperature"
      id: my_temp_sensor
    humidity:
      name: "Living Room Humidity"
    update_interval: 60s
    

# Configure the outputs
output:
  - platform: ledc
    pin: GPIO2
    id: fan_pwm_output
    frequency: 1000Hz
  - platform: gpio
    pin: GPIO0
    id: cooler_output
  - platform: gpio
    pin: GPIO4
    id: heater_output
  - platform: gpio
    pin: GPIO5
    id: fan_low_output
  - platform: gpio
    pin: GPIO25
    id: fan_medium_output
  - platform: gpio
    pin: GPIO26
    id: fan_high_output
  - platform: gpio
    pin: GPIO12
    id: swing_vertical_output
  - platform: gpio
    pin: GPIO14
    id: swing_horizontal_output
  - platform: gpio
    pin: GPIO32
    id: osc_output
  - platform: gpio
    pin: GPIO33
    id: dir_output


switch:
  - platform: template
    name: "Heat Modu"
    id: heater_switch
    turn_on_action:
      - output.turn_on: heater_output
    turn_off_action:
      - output.turn_off: heater_output

  - platform: template
    name: "Cool Modu"
    id: cooler_switch
    turn_on_action:
      - output.turn_on: cooler_output
    turn_off_action:
      - output.turn_off: cooler_output

# Swing kontrol체
  - platform: template
    name: "Swing Vertical"
    id: swing_vertical_switch
    turn_on_action:
      - output.turn_on: swing_vertical_output
    turn_off_action:
      - output.turn_off: swing_vertical_output

  - platform: template
    name: "Swing Horizontal"
    id: swing_horizontal_switch
    turn_on_action:
      - output.turn_on: swing_horizontal_output
    turn_off_action:
      - output.turn_off: swing_horizontal_output

  - platform: template
    name: "Fan Speed Low"
    id: fan_speed_low_switch
    turn_on_action:
      - output.turn_on: fan_low_output
    turn_off_action:
      - output.turn_off: fan_low_output
  - platform: template
    name: "Fan Speed Medium"
    id: fan_speed_medium_switch
    turn_on_action:
      - output.turn_on: fan_medium_output
    turn_off_action:
      - output.turn_off: fan_medium_output
  - platform: template
    name: "Fan Speed High"
    id: fan_speed_high_switch
    turn_on_action:
      - output.turn_on: fan_high_output
    turn_off_action:
      - output.turn_off: fan_high_output


climate:
  - platform: thermostat
    name: "Thermostat Climate Controller"
    sensor: my_temp_sensor
    min_cooling_off_time: 300s
    min_cooling_run_time: 300s
    min_heating_off_time: 300s
    min_heating_run_time: 300s
    min_idle_time: 30s
    min_fanning_off_time: 30s
    min_fanning_run_time: 30s
    cool_action:
      - switch.turn_on: cooler_switch
    heat_action:
      - switch.turn_on: heater_switch
    idle_action:
      - switch.turn_off: cooler_switch
      - switch.turn_off: heater_switch
    dry_action:
      - switch.turn_off: cooler_switch
      - switch.turn_off: heater_switch
    fan_only_action:
      - switch.turn_off: cooler_switch
      - switch.turn_off: heater_switch
    min_fan_mode_switching_time: 20s
    startup_delay: true
    fan_mode_off_action:
      - switch.turn_off: fan_speed_low_switch
      - switch.turn_off: fan_speed_medium_switch
      - switch.turn_off: fan_speed_high_switch
    fan_mode_on_action:
      - switch.turn_on: fan_speed_low_switch
      - switch.turn_off: fan_speed_medium_switch
      - switch.turn_off: fan_speed_high_switch
    fan_mode_low_action:
      - switch.turn_on: fan_speed_low_switch
      - switch.turn_off: fan_speed_medium_switch
      - switch.turn_off: fan_speed_high_switch
    fan_mode_medium_action:
      - switch.turn_off: fan_speed_low_switch
      - switch.turn_on: fan_speed_medium_switch
      - switch.turn_off: fan_speed_high_switch
    fan_mode_high_action:
      - switch.turn_off: fan_speed_low_switch
      - switch.turn_off: fan_speed_medium_switch
      - switch.turn_on: fan_speed_high_switch
    fan_mode_auto_action:
      - switch.turn_off: fan_speed_low_switch
      - switch.turn_off: fan_speed_medium_switch
      - switch.turn_off: fan_speed_high_switch
    swing_off_action:
      - switch.turn_off: swing_horizontal_switch
      - switch.turn_off: swing_vertical_switch
    swing_horizontal_action:
      - switch.turn_on: swing_horizontal_switch
      - switch.turn_off: swing_vertical_switch
    swing_vertical_action:
      - switch.turn_off: swing_horizontal_switch
      - switch.turn_on: swing_vertical_switch
    swing_both_action:
      - switch.turn_on: swing_horizontal_switch
      - switch.turn_on: swing_vertical_switch

    default_preset: Home
    preset:
      - name: Home
        default_target_temperature_low: 20 째C
        default_target_temperature_high: 22 째C

# Fan kontrol체 (manuel ayarlanabilir)
fan:
  - platform: speed
    output: fan_pwm_output
    name: "Meeting Room Fan"
    id: pwm_fan
    restore_mode: ALWAYS_OFF
    oscillation_output: osc_output
    direction_output: dir_output
    speed_count: 25
  - platform: binary
    name: "Fan Low"
    output: fan_low_output
  - platform: binary
    name: "Fan Medium"
    output: fan_medium_output
  - platform: binary
    name: "Fan High"
    output: fan_high_output


# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "GSpzSeXxc74i2dNzd2jmaxIc0AB2az8MUM8Sgu6ctmA="

ota:
  - platform: esphome
    password: "Yilmaz"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32S-Climate Fallback Hotspot"
    password: "Asx12345678?."

captive_portal:
    